### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [kellenweagle/heirbnb-aa#1]
# API Docs:
Looks good! Approved!

## Tasks:
- [x] Create RESTFUL backend routes
- [x] Add DB Diagram to docs
- [x] Add methods to docs

 
# DB Diagram:
Looking really good! Just missing some functionality in the way `previewImage` would work, based on the docs. 

## Tasks
- [x] Adjust the way we can check for `previewImages`. This is referenced in the docs, but we have no way of checking for it as of now. Consider if it will go on the `Spots` Table or `SpotImages` table. A `Spot` may have multiple preview Images. 

# Deadline
Please aim to complete the listed tasks by EOD on Monday, May 13th as we are looking to have all documentations approved in order to move on to the next phase of our project life cycle the following day.

**Comment by irelius** [comment]
# API Docs and DB Diagram Review 2

## DB Diagram
- [x] Tables should be capitalized (e.g. "Users" instead of "users")
- [x] Certain table names do not match the API docs (e.g. "spotImgs" and "reviewImgs")
- [x] The "password" column under the Users table should be "hashedPassword". This is to make it more clear that we'll be storing passwords after they've been salted and hashed (we should never store passwords as plaintext in our database). While you could just call the column "password" and store salted & hashed passwords, it's best to make it clear
- [x] The "stars" data type under Reviews should be an integer. While the average rating can be a decimal, users should just be able to rate a spot 1 - 5 (no 3.5s or such)
- [x] The "reviewImgUrl" column name under the ReviewImgs table does not match the API docs
- [x] The "spotImgUrl" column name under the SpotImgs table does not match the API docs
- [x] The "price" column under the Spots table should be a decimal data type, not integer to account for cents

## API Docs
Everything looks good. Nice!
- [x] Add the new DB Diagram once all those changes are done
